################################################################################
# This file is released under the GNU General Public License, Version 3, GPL-3 #
# Copyright (C) 2021 Yohann Demont                                             #
#                                                                              #
# It is part of IFCshiny package, please cite:                                 #
#  -IFCshiny: An R Interactive Shiny Application for the Analysis of Imaging   #
#             and Conventional Flow Cytometry                                  #
#  -YEAR: 2021                                                                 #
#  -COPYRIGHT HOLDERS: Yohann Demont, Jean-Pierre Marolleau, Loïc Garçon,      #
#                      CHU Amiens                                              #
#                                                                              #
# DISCLAIMER:                                                                  #
#  -You are using this package on your own risk!                               #
#  -We do not guarantee privacy nor confidentiality.                           #
#  -This program is distributed in the hope that it will be useful, but WITHOUT#
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE. In no event shall the copyright holders or #
# contributors be liable for any direct, indirect, incidental, special,        #
# exemplary, or consequential damages (including, but not limited to,          #
# procurement of substitute goods or services; loss of use, data, or profits;  #
# or business interruption) however caused and on any theory of liability,     #
# whether in contract, strict liability, or tort (including negligence or      #
# otherwise) arising in any way out of the use of this software, even if       #
# advised of the possibility of such damage.                                   #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with IFCshiny. If not, see <http://www.gnu.org/licenses/>.             #
################################################################################

list(hidden(absolutePanel(id = "comp_manager",
                          width = "500px", height = "500px",
                          draggable = TRUE, top = 0, left = 0, right = 0, bottom = 0,
                          tags$div(style = "position:absolute; top:0px; left:0px; background-color:white; width:500px; height:500px; border-radius:5px; padding:10px 10px 10px 10px;",
                                   tags$div(style = "position:absolute; left:50%; top:10px; transform: perspective(1px) translate(-50%); z-index:2;",
                                            tags$p(style="text-align: center; font-weight: bold;",
                                                      "Use slider to tweak compensation"),
                                            plotOutput("comp_plot", width = "400px", height= "400px"))
                          ),
                          tags$div(style = "position:absolute; bottom:10px; left:50%; transform: perspective(1px) translateX(-50%); z-index:2;",
                                   shinyWidgets::noUiSliderInput(inputId = "comp_sliderX", label = NULL,
                                                                 min = -10, max = +100, value = 0, step = 0.1,
                                                                 orientation = "horizontal", direction = "rtl",
                                                                 width = "400px"
                                   )
                          ),
                          tags$div(style = "position:absolute; right:10px; top:50%; transform: perspective(1px) translateY(-50%); z-index:2;",
                                   shinyWidgets::noUiSliderInput(inputId = "comp_sliderY", label = NULL, 
                                                                 min = -10, max = +100, value = 0, step = 0.1,
                                                                 orientation = "vertical", direction = "ltr",
                                                                 width = "50px",
                                                                 height = "400px"
                                   )
                          ),
                          tags$div(class="ctrl_btn",
                                   style="position:absolute; top:10px; left:10px;",
                                   # tags$div(style = "display: inline-block; vertical-align: middle;",
                                   # actionButton(inputId = "reduce", label = NULL, icon = icon("window-minimize", lib = "font-awesome"), class = "red")),
                                   # tags$div(style = "display: inline-block; vertical-align: middle;",
                                   # actionButton(inputId = "maximize", label =NULL, icon = icon("window-maximize", lib = "font-awesome"), class = "max")), #"\u2610"
                                   tags$div(style = "display: inline-block; vertical-align: middle;",
                                            actionButton(style="color:red;", inputId = "comp_close", label = NULL, icon = icon("window-close", lib = "font-awesome"), class = "clo")))
)),
hidden(absolutePanel(id = "cell_manager", class = "panel panel-default", fixed = FALSE,
                     style = "z-index:99; width:500px; height:290px; padding:10px 10px 10px 10px;",
                     draggable = TRUE, top = 0, left = 0, right = 0, bottom = 0,
                     tags$div(id = "cell_image_placeholder", style = "position:absolute; top:290px;"),
                     tags$h4("Cell Manager"),
                     fluidRow(
                       column(width = 6, align = "left",
                              style = "float:left; top:18px",
                              tags$div(class="cell_left",
                                       selectInput(inputId = "cell_population", label = "Pop to display", choices = list(), multiple = FALSE),
                                       tags$div(id = "cell_sort",
                                                tags$div(style = "display:inline-block; vertical-align:sub; width:80%",
                                                         selectInput(inputId = "cell_feature", label = "Feature value", choices = "Object Number", multiple = FALSE)),
                                                tags$div(style = "display:inline-block; vertical-align:text-bottom; left:81%; width:10%",
                                                         actionButton(inputId = "cell_feature_sort", label = "", icon = icon(name="sort-amount-down-alt", lib="font-awesome")))
                                       ),
                                       tags$div(style = "text-align: left;",
                                                # tags$div(style = "display: inline-block; width:25%; vertical-align:middle;",
                                                #          selectInput(inputId = "cell_channels", label = "Channel", choices = c(1:12), selected = NULL, multiple = FALSE)),
                                                tags$div(style = "display: inline-block; width:30%; vertical-align:baseline;",
                                                         numericInput(inputId = "cell_page", label = "Page", min = 1, max = 1, step = 1, value = 1)),
                                                tags$div(style = "display: inline-block; width:25%; vertical-align:baseline;",
                                                         numericInput(inputId = "cell_grid", label = "Grid", min = 1, max = 7, step = 1, value = 7)),
                                                tags$div(style = "text-align: right; display: inline-block; width:10%; vertical-align:2px;",
                                                         actionButton(inputId = "cell_settings", label = NULL, icon = icon(name="adjust", lib="font-awesome")))
                                       )
                                       
                              )),
                       column(width = 6, align = "right",
                              style = "float:left;",
                              tags$div(class="cell_right",
                                       tags$div(tags$div(tags$div(style = "display: inline-block; width:49%;",
                                                                  sliderInput(inputId = "cell_height", label = "height", min = 1, max = 200, value = 64)),
                                                         tags$div(style = "display: inline-block; width:49%;",
                                                                  sliderInput(inputId = "cell_width", label = "width", min = 1, max = 200, value = 64)),
                                                         tags$div(tags$div(style = "display: inline-block; width:49%;",
                                                                           sliderInput(inputId = "cell_zoom", label = "zoom", min = -1, max = 1, value = 0, step=0.1)),
                                                                  tags$div(style = "display: inline-block; width:49%;",
                                                                           sliderInput(inputId = "cell_rotate", label = "rotate", min = 0, max = 90, value = 0))),
                                                         hidden(tags$div(id = "cell_pop_edit",
                                                                         tags$div(style="display:inline-block; text-align:left; position:relative; top:-20px; width:80%;",
                                                                                  selectInput(inputId="cell_pop_tagged", label = "", choices = list(), multiple = FALSE)),
                                                                         tags$div(style="display:inline-block; text-align:left; position:relative; vertical-align:top; width:18%;",
                                                                                  actionButton(inputId = "cell_modify", label = "", icon = icon("share-square", lib = "font-awesome"))))),
                                                         (tags$div(id = "cell_pop_create",
                                                                   tags$div(style="display:inline-block; ",
                                                                            tags$b("Create new"),
                                                                            tags$div(style="display:inline-block; ",
                                                                                     actionButton(inputId = "cell_create", label = "", icon = icon("plus-circle", lib = "font-awesome"))))))
                                       ))
                              ))),
                     tags$div(style="display:inline-block; text-align:left; position:absolute; top:12px; left:130px; width:200px;",
                              switchInput(inputId = "cell_mode", label = "", onLabel = "edit", offLabel = "create", onStatus = "info", offStatus = "info", value = FALSE)),
                     tags$div(class="ctrl_btn",
                              style="position:absolute; top:10px; right:10px;",
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "reduce", label = NULL, icon = icon("window-minimize", lib = "font-awesome"), class = "red")),
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "maximize", label =NULL, icon = icon("window-maximize", lib = "font-awesome"), class = "max")), #"\u2610"
                              tags$div(style = "display: inline-block; vertical-align: middle;",
                                       actionButton(style="color:red;", inputId = "cell_close", label = NULL, icon = icon("window-close", lib = "font-awesome"), class = "clo")))
)),
hidden(absolutePanel(id = "reg_manager", class = "panel panel-default", fixed = FALSE,
                     style = "z-index:99; width:500px; height:max-content; padding:10px 10px 10px 10px;",
                     # tags$div(class ="ctrl_channels",
                     # style = "position:absolute; top:10px; left:10px; background-color:lightblue; width:400px; height:160px; border-radius:5px; padding:10px 10px 10px 10px;",
                     draggable = TRUE, top = 0, left = 0, right = 0, bottom = 0,
                     tags$h4("Region Manager"),
                     fluidRow(
                       column(width = 6,
                              tags$h3("Region Info"),
                              tags$div(#style = "display: inline-block; vertical-align: bottom; width:70%;",
                                tags$div(class = "reg_selection",
                                         selectInput(inputId = "reg_selection", label = "Region", choices = c(""), multiple = FALSE, selected = NULL))),
                              tags$div(#style = "display: inline-block; vertical-align: bottom; width:48%;",
                                tags$div(class = "reg_def_label",
                                         tags$div(style = "display: inline-block; vertical-align: 1px; width:27%;",
                                                  actionButton(class="reg_def_reset", inputId = "reg_def_label_reset", label = "Reset")),
                                         tags$div(style = "display: inline-block; vertical-align: baseline; width:71%;",
                                                  textInput(inputId = "reg_def_label", label = "Name", value = character()))),
                                tags$div(class = "reg_def_cx",
                                         tags$div(style = "display: inline-block; vertical-align: 1px; width:27%;",
                                                  actionButton(class="reg_def_reset", inputId = "reg_def_cx_reset", label = "Reset")),
                                         tags$div(style = "display: inline-block; vertical-align: baseline; width:71%;",
                                                  numericInput(inputId = "reg_def_cx", label = "Label x", value = numeric()))),
                                tags$div(class = "reg_def_cy",
                                         tags$div(style = "display: inline-block; vertical-align: 1px; width:27%;",
                                                  actionButton(class="reg_def_reset", inputId = "reg_def_cy_reset", label = "Reset")),
                                         tags$div(style = "display: inline-block; vertical-align: baseline;  width:71%;",
                                                  numericInput(inputId = "reg_def_cy", label = "Label y", value = numeric()))),
                                tags$div(class = "reg_def_viz",
                                         verbatimTextOutput(outputId = "reg_def_viz")))),
                       column(width = 6, align = "right",
                              style = "float:right;",
                              tags$div(class="reg_style",
                                       tags$div(class="reg_colors",
                                                tags$div(style = "display: inline-block; vertical-align: super; width:48%;",
                                                         tags$div(style = "position:absolute; top: 12px;",
                                                                  actionButton(class="reg_def_reset undo transparent", inputId = "reg_color_light_reset", label = NULL, icon = icon("undo", lib = "font-awesome"))),
                                                         colourpicker::colourInput(inputId = "reg_color_light", label = "Light Mode Color", showColour = "background", value = "Red",
                                                                                   returnName = TRUE, allowTransparent = FALSE, palette = "limited", allowedCols = unique(unlist(paletteIFC()[,  c("color_R",  "lightModeColor_R")])))),
                                                tags$div(style = "display: inline-block; vertical-align: super; width:48%;",
                                                         tags$div(style = "position:absolute; top: 12px;",
                                                                  actionButton(class="reg_def_reset undo transparent", inputId = "reg_color_dark_reset", label = NULL, icon = icon("undo", lib = "font-awesome"))),
                                                         colourpicker::colourInput(inputId = "reg_color_dark", label = "Dark Mode Color", showColour = "background", value = "Red",
                                                                                   returnName = TRUE, allowTransparent = FALSE, palette = "limited", allowedCols = unique(unlist(paletteIFC()[,  c("color_R",  "lightModeColor_R")])))))),
                              tags$div(class = "reg_def_table",
                                       tags$div(class = "reg_def_feedback",
                                                style="text-align: left;", 
                                                tags$div(style = "display: inline-block; vertical-align: text-bottom; width:27%;",
                                                         actionButton(class="reg_def_reset", inputId = "reg_def_table_reset", label = "Reset")),
                                                tags$div(style = "display: inline-block; vertical-align: sub;  width:71%;",
                                                         "data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Double click to edit.",
                                                         selectInput(inputId = "reg_def_table_feedback", label = "", choices = c("Coords"), selected = "Coords", multiple = FALSE))),
                                       tags$div("data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="double click to edit",
                                                DT::dataTableOutput(outputId = "reg_def_table"))))),
                     tags$div(class = "reg_btn",
                              style = "display: inline-block; vertical-align: middle;",
                              actionButton(inputId = "reg_remove", label = "Remove"),
                              actionButton(inputId = "reg_validate", label = "Validate")),
                     tags$div(class="ctrl_btn",
                              style="position:absolute; top:10px; right:10px;",
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "reduce", label = NULL, icon = icon("window-minimize", lib = "font-awesome"), class = "red")),
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "maximize", label =NULL, icon = icon("window-maximize", lib = "font-awesome"), class = "max")), #"\u2610"
                              tags$div(style = "display: inline-block; vertical-align: middle;",
                                       actionButton(style="color:red;", inputId = "reg_close", label = NULL, icon = icon("window-close", lib = "font-awesome"), class = "clo")))
)),
hidden(absolutePanel(id = "graph_manager", class = "panel panel-default", fixed = FALSE,
                     style = "z-index:99; width:500px; height:max-content; padding:10px 10px 10px 10px;",
                     # tags$div(class ="ctrl_channels",
                     # style = "position:absolute; top:10px; left:10px; background-color:lightblue; width:400px; height:160px; border-radius:5px; padding:10px 10px 10px 10px;",
                     draggable = TRUE, top = 0, left = 0, right = 0, bottom = 0,
                     tags$h4("Graph Manager"),
                     fluidRow(
                       column(width = 6,
                              tags$div(tags$div(style = "display: inline-block; width:50%; float:left;",
                                                numericInput(inputId = "plot_xmin", label = "min xlim", value = numeric())),
                                       tags$div(style = "display: inline-block; width:50%; float:right; text-align:right",
                                                numericInput(inputId = "plot_xmax", label = "max xlim", value = numeric()))),
                              tags$div(class= "plot_density plot_density_gradient",
                                       tags$div(style="display:inline-block;vertical-align:sub; width:80%;",
                                                selectInput(inputId = "plot_dens_color", label = "gradient",
                                                            choices = na.omit(c("initial",ifelse(rep(requireNamespace("viridisLite", quietly = TRUE), 8), c("cividis","inferno","magma","mako","plasma","rocket","turbo","viridis"), rep(NA, 8)),
                                                                        rownames(RColorBrewer::brewer.pal.info))), selected = "initial", multiple = FALSE)),
                                       tags$div(style="display:inline-block;vertical-align:text-bottom; width:18%;",
                                                actionButton(inputId = "plot_dens_order", label = NULL, icon = icon("exchange-alt", lib = "font-awesome")))),
                              tags$div(id="plot_fonts",
                                       tags$div(tags$h4("Font sizes")),
                                       tags$div(tags$div(selectInput(inputId = "plot_font_main", label = "Title", choices = c(8,9,10,11,12,14,16,18,20,22,24,26,28), selected = 12, multiple = FALSE)),
                                                tags$div(selectInput(inputId = "plot_font_axis_lab", label = "Axis Labels", choices = c(8,9,10,11,12,14,16,18,20,22,24,26,28), selected = 10, multiple = FALSE)),
                                                tags$div(selectInput(inputId = "plot_font_tick_lab", label = "Tick Labels", choices = c(8,9,10,11,12,14,16,18,20,22,24,26,28), selected = 10, multiple = FALSE)),
                                                tags$div(selectInput(inputId = "plot_font_region", label = "Region Names", choices = c(8,9,10,11,12,14,16,18,20,22,24,26,28), selected = 10, multiple = FALSE))))
                       ),
                       column(width = 6, align = "right",
                              style = "float:right;",
                              tags$div(tags$div(style = "display: inline-block; width:50%; float:left;",
                                                numericInput(inputId = "plot_ymin", label = "min ylim", value = numeric())),
                                       tags$div(style = "display: inline-block; width:50%; float:right; text-align:right",
                                                numericInput(inputId = "plot_ymax", label = "max ylim", value = numeric()))),
                              tags$div(
                                class= "plot_density plot_density_level",
                                tags$div(
                                  tags$div(style = "display: inline-block; width:50%; float:left;",
                                           numericInput(inputId = "plot_level_nlevels", label = "levels", value = 10, min = 1)),
                                  tags$div(style = "display: inline-block; width:50%; float:right; text-align:right",
                                           numericInput(inputId = "plot_level_lowest", label = "lowest", value = 0.1, min = 0, max = 0.95, step = 0.05))),
                                tags$div(
                                  tags$div(style = "display: inline-block; width:49%; text-align:right",
                                           prettyCheckbox(inputId="plot_level_fill", label="Fill", value=TRUE, status="success",shape="curve",outline=TRUE)),
                                  tags$div(style = "display: inline-block; width:49%; text-align:right", 
                                           prettyCheckbox(inputId="plot_level_lines", label="lines", value=FALSE, status="success",shape="curve",outline=TRUE)))
                                ),
                              tags$div(class= "plot_density plot_density_feature",
                                       tags$div(style="text-align:left;",
                                                selectInput(inputId = "plot_dens_feature", label = "marker", choices = c("initial","default"), selected = c("initial","default"), multiple = FALSE))),
                              tags$div(id="plot_labels",
                                       tags$div(tags$h4("Labels")),
                                       tags$div(tags$div(textInput(inputId = "plot_lab_main", label = "Title", value = character())),
                                                tags$div(textInput(inputId = "plot_lab_x", label = "X Axis Label", value = character())),
                                                tags$div(textInput(inputId = "plot_lab_y", label = "Y Axis Label", value = character()))))
                       )),
                     # tags$div(class = "reg_btn",
                     #          style = "display: inline-block; vertical-align: middle;",
                     #          # actionButton(inputId = "reg_remove", label = "Remove"),
                     #          # actionButton(inputId = "reg_validate", label = "Validate")),
                     tags$div(class="ctrl_btn",
                              style="position:absolute; top:10px; right:10px;",
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "reduce", label = NULL, icon = icon("window-minimize", lib = "font-awesome"), class = "red")),
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "maximize", label =NULL, icon = icon("window-maximize", lib = "font-awesome"), class = "max")), #"\u2610"
                              tags$div(style = "display: inline-block; vertical-align: middle;",
                                       actionButton(style="color:red;", inputId = "graph_close", label = NULL, icon = icon("window-close", lib = "font-awesome"), class = "clo")))
)),
hidden(absolutePanel(id = "pop_manager", class = "panel panel-default", fixed = FALSE,
                     style = "z-index:99; width:500px; height:max-content; padding:10px 10px 10px 10px;",
                     # tags$div(class ="ctrl_channels",
                     # style = "position:absolute; top:10px; left:10px; background-color:lightblue; width:400px; height:160px; border-radius:5px; padding:10px 10px 10px 10px;",
                     
                     draggable = TRUE, top = 0, left = 0, right = 0, bottom = 0,
                     tags$h4("Population Manager"),
                     fluidRow(
                       column(width = 7,
                              tags$div(class = "pop_symbol",
                                       tags$div(style = "display: inline-block; vertical-align: text-bottom; width:23%;",
                                                actionButton(class="pop_def_reset", inputId = "pop_symbol_reset", label = "Reset")),
                                       tags$div(style = "display: inline-block; vertical-align: sub; width:75%;",
                                                selectInput(inputId = "pop_symbol", label = "Symbol", choices = c("Simple Dot", "Cross", "Plus", 
                                                                                                                  "Empty Circle", "Empty Diamond", "Empty Square", 
                                                                                                                  "Empty Triangle", "Solid Diamond", "Solid Square", 
                                                                                                                  "Solid Triangle"), multiple = FALSE, selected = NULL))),
                              tags$div(class = "pop_def_name",
                                       tags$div(style = "display: inline-block; vertical-align: 1px; width:23%;",
                                                actionButton(class="pop_def_reset", inputId = "pop_def_name_reset", label = "Reset")),
                                       tags$div(style = "display: inline-block; vertical-align: baseline; width:75%;",
                                                textInput(inputId = "pop_def_name", label = "Name"))),
                              tags$div(class = "pop_def_feedback",
                                       tags$div(style = "display: inline-block; vertical-align: text-bottom; width:23%;",
                                                actionButton(class="pop_def_reset", inputId = "pop_def_reset", label = "Reset")),
                                       tags$div(style = "display: inline-block; vertical-align: sub;  width:75%;",
                                                "data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Click to build your population.",
                                                selectInput(inputId = "pop_def_feedback", label = "Definition", choices = c("Boolean"), selected = "Boolean", multiple = FALSE)))),
                       column(width = 5, 
                              align = "right",
                              style = "float:right;",
                              tags$div(class="pop_colors",
                                       # style = "display: inline-block; vertical-align: text-bottom; width:20%;",
                                       tags$div(style = "display: inline-block; vertical-align: super; width:48%;",
                                                tags$div(style = "position:absolute; top: 12px;",
                                                         actionButton(class="pop_def_reset undo transparent", inputId = "pop_color_light_reset", label = NULL, icon = icon("undo", lib = "font-awesome"))),
                                                colourpicker::colourInput(inputId = "pop_color_light", label = "Light Mode Color", showColour = "background", value = "Red",
                                                                          returnName = TRUE, allowTransparent = FALSE, palette = "limited", allowedCols = unique(unlist(paletteIFC()[,  c("color_R",  "lightModeColor_R")])))),
                                       tags$div(style = "display: inline-block; vertical-align: super; width:48%;",
                                                tags$div(style = "position:absolute; top: 12px;",
                                                         actionButton(class="pop_def_reset undo transparent", inputId = "pop_color_dark_reset", label = NULL, icon = icon("undo", lib = "font-awesome"))),
                                                colourpicker::colourInput(inputId = "pop_color_dark", label = "Dark Mode Color", showColour = "background", value = "Red",
                                                                          returnName = TRUE, allowTransparent = FALSE, palette = "limited", allowedCols = unique(unlist(paletteIFC()[,  c("color_R",  "lightModeColor_R")]))))))),
                     tags$div(id = "pop_def_edit",
                              style="position:relative; display:inline-block;",
                              tags$div(class = "pop_def_sel",
                                       style="position:relative; vertical-align:middle; display:inline-block; width:34%",
                                       selectInput(inputId = "pop_def_sel", label = "", choices = list(), selected = NULL, multiple = FALSE)),
                              tags$div(class = "pop_def_btn",
                                       style="position:relative; vertical-align:middle; display:inline-block; width:64%",
                                       tags$div("data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Add",
                                                style="position: relative; display: inline-block;",
                                                actionButton(inputId = "pop_def_add", label = NULL, icon("angle-double-down", lib = "font-awesome"))),
                                       tags$div("data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="And",
                                                style="position: relative; display: inline-block;",
                                                actionButton(inputId = "pop_def_and", label = NULL, icon("users", lib = "font-awesome"))),
                                       tags$div("data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Or",
                                                style="position: relative; display: inline-block;",
                                                actionButton(inputId = "pop_def_or", label = NULL, icon("restroom", lib = "font-awesome"))),
                                       tags$div("data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Not",
                                                style="position: relative; display: inline-block;",
                                                actionButton(inputId = "pop_def_not", label = NULL, icon("user-slash", lib = "font-awesome"))),
                                       tags$div("data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="(",
                                                style="position: relative; display: inline-block;",
                                                actionButton(inputId = "pop_def_bkt1", label = NULL, icon("chevron-left", lib = "font-awesome"))),
                                       tags$div("data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"=")",
                                                style="position: relative; display: inline-block;",
                                                actionButton(inputId = "pop_def_bkt2", label = NULL, icon("chevron-right", lib = "font-awesome"))),
                                       tags$div("data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Remove",
                                                style="position: relative; display: inline-block;",
                                                actionButton(inputId = "pop_def_rm", label = NULL, icon("backspace", lib = "font-awesome")))
                              )
                     ),
                     tags$div(class = "pop_def_viz",
                              verbatimTextOutput(outputId = "pop_def_viz")),
                     tags$div(class = "pop_btn",
                              fluidRow(column(width = 7,
                                              tags$div(style = "display: inline-block; vertical-align: middle;",
                                                       actionButton(inputId = "pop_remove", label = "Remove"),
                                                       actionButton(inputId = "pop_validate", label = "Validate"))),
                                       column(width = 5,align = "right",
                                              style = "float:right;",
                                              tags$div(style = "display: inline-block; vertical-align: middle;",
                                                       actionButton(inputId = "pop_plot", label = "Plot it")),
                                              tags$div(style = "display: inline-block; vertical-align: middle;",
                                                       actionButton(inputId = "pop_tag", label = "Re-tag it"))))),
                     tags$div(class="ctrl_btn",
                              style="position:absolute; top:10px; right:10px;",
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "reduce", label = NULL, icon = icon("window-minimize", lib = "font-awesome"), class = "red")),
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "maximize", label =NULL, icon = icon("window-maximize", lib = "font-awesome"), class = "max")), #"\u2610"
                              tags$div(style = "display: inline-block; vertical-align: middle;",
                                       actionButton(style="color:red;", inputId = "pop_close", label = NULL, icon = icon("window-close", lib = "font-awesome"), class = "clo")))
)),
hidden(absolutePanel(id = "img_manager", class = "panel panel-default", fixed = FALSE,
                     style = "z-index:99;",
                     draggable = TRUE, top = 0, left = 0, right = 0, bottom = 0,
                     width = "800px", height = "600px",
                     tags$div(class ="ctrl_channels",
                              style = "position:absolute; top:10px; left:10px; background-color:lightblue; width:400px; height:160px; border-radius:5px; padding:10px 10px 10px 10px;",
                              tags$h4("Global"),
                              tags$div(class="multicol",
                                       checkboxGroupInput(inputId = "channels", label = NULL, choices = sprintf("%02i",1:12))),
                              tags$div(style = "position:absolute; display:inline-block; top:130px; left:0px;",
                                       "data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Select whether to show images or masks",
                                       radioButtons(inputId = "chan_type", label = NULL, choices = c("img","msk"), selected = "img")),
                              tags$div(style = "position:absolute; display:inline-block; left:220px; width:80px; top:20px;",
                                       tags$div(numericInput(inputId = "chan_cell_todisplay", label = "Cell #", min = 0, value = 0))),
                              tags$div(style = "position:absolute; display:inline-block; left:220px; width:80px; top:90px;",
                                       "data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Image height, leave 0 to get image at its full height",
                                       tags$div(numericInput(inputId = "chan_height", label = "height", min = 0, value = 0))),
                              tags$div(style = "position:absolute; display:inline-block; left:310px; width:80px; top:90px;",
                                       "data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="Image width, leave 0 to to use default channel width",
                                       tags$div(numericInput(inputId = "chan_width", label = "width", min = 0, value = 0)))),
                     tags$div(class="ctrl_inputs",
                              style = "position:absolute; width:47%; bottom:80px; left:2%;",
                              tags$div(style = "position:relative; display:inline-block;",# top:0px; left:0px;",
                                       "data-toggle"="tooltip", "data-placement"="top", "data-html"="true", "title"="These options are mutualy exclusive and controls image range. With 'force_range' image will be scaled to its min/max value, with 'full_range' image will be scaled to [0-4095].",
                                       checkboxGroupInput(inputId = "chan_force", inline = TRUE, label = NULL, choices = c("full_range","force_range"))),
                              tags$div(style = "",
                                       tags$div(style = "position:relative; display: inline-block; vertical-align: text-bottom;",
                                                actionButton(class="controls_g_resets", inputId = "reset_gamma", label = "Reset")),
                                       tags$div(style = "position:relative; display: inline-block; vertical-align: middle; width:35%;",
                                                sliderInput(inputId = "chan_gamma_x", label = "GammaX", value = 0, min = 0, max = 4095)),
                                       tags$div(style = "position:relative; display: inline-block; vertical-align: middle; width:35%; right: -10%;",
                                                sliderInput(inputId = "chan_gamma_y", label = "GammaY", value = 127, min = 0, max = 255))
                              ),
                              tags$div(style="",
                                       tags$div(style = "display: inline-block; vertical-align: text-bottom;",
                                                actionButton(class="controls_r_resets", inputId = "reset_range", label = "Reset")),
                                       tags$div(style = "display: inline-block; vertical-align: middle;",
                                                sliderInput(inputId = "chan_range", label = "Range", value = c(0,4095), min = 0, max = 4095))
                              ),
                              tags$div(style="",
                                       tags$div(style = "display: inline-block; vertical-align: text-bottom;",
                                                actionButton(class="controls_v_resets", inputId = "reset_view", label = "Reset")),
                                       tags$div(style = "display: inline-block; vertical-align: middle;",
                                                sliderInput(inputId = "chan_view", label = "View", value = c(0,4095), min = 0, max = 4095))
                              )
                     ),
                     tags$div(class="ctrl_graphs",
                              style="position:absolute; width:47%; height:350px; bottom:40px; right:2%;",
                              tags$div(id="controls_cell", 
                                       style = "position:relative; top: -120px;",
                                       img(id = "chan_cell_image", src = "", style = "display: block; margin: 0 auto;")),
                              tags$div(id="controls_plot", 
                                       style = "position:relative;",
                                       plotOutput(outputId = "chan_cell_range", height = "200px"))),
                     tags$div(style = "position:absolute; bottom:5px; left:2%; width:96%",
                              tags$div(style = "display: inline-block; vertical-align: baseline;",
                                       actionButton(class="controls_c_resets", inputId = "reset_name", label = "Reset")),
                              tags$div(style = "display: inline-block; vertical-align: baseline; width:38%;",
                                       textInput(inputId = "chan_name", label = "Channel name", value = "")),
                              tags$div(style = "display: inline-block; vertical-align: baseline;  width:15%; float: right; text-align:left;",
                                       selectInput(inputId = "chan_sel", label = "Channel #", choices = list())),
                              tags$div(style = "display: inline-block; vertical-align: baseline; width:15%; text-align:left; float: right;",
                                       tags$div(style = "position:absolute; top:-8px; text-align:right; width:14%",
                                                actionButton(class="controls_c_resets undo transparent", inputId = "reset_color", label = NULL, icon = icon("undo", lib = "font-awesome"))),
                                       colourpicker::colourInput(inputId = "chan_color", label = "Color", showColour = "background", value = "Red",
                                                                 returnName = TRUE, allowTransparent = FALSE, palette = "limited", allowedCols = unique(unlist(paletteIFC()[,  c("color_R",  "lightModeColor_R")]))))),
                     tags$div(class="ctrl_btn",
                              style="position:absolute; top:10px; right:10px;",
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "reduce", label = NULL, icon = icon("window-minimize", lib = "font-awesome"), class = "red")),
                              # tags$div(style = "display: inline-block; vertical-align: middle;",
                              # actionButton(inputId = "maximize", label =NULL, icon = icon("window-maximize", lib = "font-awesome"), class = "max")), #"\u2610"
                              tags$div(style = "display: inline-block; vertical-align: middle;",
                                       actionButton(style="color:red;", inputId = "img_close", label = NULL, icon = icon("window-close", lib = "font-awesome"), class = "clo")))
)))